# permissions for end users to view cronverticalpodautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronverticalpodautoscaler-viewer-role
rules:
- apiGroups:
  - autoscaling.zoublog.com
  resources:
  - cronverticalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.zoublog.com
  resources:
  - cronverticalpodautoscalers/status
  verbs:
  - get
