# permissions for end users to edit cronverticalpodautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronverticalpodautoscaler-editor-role
rules:
- apiGroups:
  - autoscaling.zoublog.com
  resources:
  - cronverticalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.zoublog.com
  resources:
  - cronverticalpodautoscalers/status
  verbs:
  - get
