---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - verticalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - verticalpodautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscaling.zoublog.com
  resources:
  - cronverticalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.zoublog.com
  resources:
  - cronverticalpodautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.zoublog.com
  resources:
  - cronverticalpodautoscalers/status
  verbs:
  - get
  - patch
  - update
