apiVersion: autoscaling.zoublog.com/v1alpha1
kind: CronVerticalPodAutoscaler
metadata:
  name: cronvpa-2
spec:
  initialJob: "Los_Angeles-Test"
  keepUpdated: true
  jobs:
  - name: "HongKong-Auto"
    schedules: 
    - "*/11 * * * *"
    timeZone: "Asia/Hong_Kong"
    suspend: false
    patchVPA:
      updatePolicy:
        updateMode: "Auto"
  - name: "London Initial"
    schedules:
    - "21 * * * *"
    excludedDates:
    - "* * * * 5"
    timeZone: "Europe/London"
    suspend: false
    patchVPA:
      updatePolicy: 
        updateMode: "Initial"
  baseVPA:
    targetRef:
      apiVersion: "apps/v1"
      kind: Deployment
      name: deploy2
    updatePolicy: 
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: '*'
          minAllowed:
            cpu: 10m
            memory: 50Mi
          maxAllowed:
            cpu: 1
            memory: 500Mi
          controlledResources: ["cpu", "memory"]
          controlledValues: RequestsOnly
